stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: maven:3-jdk-8-alpine
          shellScript: |-
            mvn clean package spring-boot:repackage
  - name: Publish
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: example-gateway:${CICD_EXECUTION_SEQUENCE}
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deployment.yaml