kind: Service
apiVersion: v1
metadata:
  name: gatway-service
  namespace: defalut
spec:
  selector:
    app: gatway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatway
  namespace: defalut
  labels:
    app: gatway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatway
  template:
    metadata:
      labels:
        app: gatway
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: gatway
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 8080